version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    command: >
      sh -c "python manage.py wait_for_db &&
                  python manage.py migrate &&
                  python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3001:3000"
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/srv/app
      - node_modules:/srv/app/node_modules
    depends_on:
      - backend

  cypress:
    image: "cypress/included:9.1.0"
    container_name: cypress
    depends_on:
      - frontend
      - backend
      - db
      - nginx
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
    command: npx cypress run
    volumes:
        - ./frontend:/app
        - ./frontend/e2e/cypress:/app/cypress
        - ./frontend/e2e/cypress.config.js:/app/cypress.config.js


  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - backend
      - frontend
      - db

volumes:
  dev-db-data:
  node_modules:
  media:
  static:
