# Generated by Django 4.0.10 on 2024-09-17 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_user(apps, schema_editor):
    amenities = apps.get_model('core', 'Amenities')
    user = apps.get_model('core', 'User')
    default_user = user.objects.first()
    amenities.objects.update(user=default_user)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_alter_cottage_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cottage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
