# Generated by Django 4.0.10 on 2024-09-17 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_default_user(apps, schema_editor):
    Amenities = apps.get_model('core', 'Amenities')
    User = apps.get_model('core', 'User')
    default_user = User.objects.first()
    Amenities.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_alter_amenities_user'),
    ]

    operations = [
        migrations.RunPython(assign_default_user),
        migrations.AlterField(
            model_name='amenities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
