# Generated by Django 4.0.10 on 2024-09-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_amenities_cottage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard'), ('luxury', 'Luxury')], default='standard', max_length=255),
        ),
    ]
